### ISSUE TITLE
I/O APIC is disable and crash the machine with 2 or more CPUs

### ISSUE THREAD

**Issue by hector-vido** [openSUSE/vagrant#45] opened 2021-03-14 22:34 UTC
Hi guys,

I didn't find where openSUSE build Vagrant images, just this repository, and it looks old, anyway we need to add I/O APIC during machine creation, or it'll crash on setips with 2 or more cpu cores.

`vb.customize ["modifyvm", :id, "--ioapic", "on"]`

**Comment by dcermak** [comment] 2021-03-15 05:56
Thanks for the heads up! I'll look into this later this week.

**Comment by dcermak** [comment] 2021-07-02 13:32
Hi @hector-vido, sorry for the long radio silence from my side. I was initially not able to reproduce any crashes and then it fell into my backlog…

Anyway, I came back to this a few days ago when debugging a terrible slowness in nested virtualization envirnoments. I hope that I have fixed the issue now and will submit fixes to the existing images. They should hopefully Vagrantcloud soon.

**Comment by hector-vido** [comment] 2021-07-04 03:16
Nice! Good to know :D

**Comment by dcermak** [comment] 2021-07-07 12:45
This should be fixed on Leap now and on Tumbleweed hopefully in a few days at most.

**Closed as completed by dcermak** 2021-07-07 12:45 UTC

**Comment by oliverhr** [comment] 2025-07-06 06:23
Hi seems this was not updated latest Tumbleweed image available `1.0.20241025` on:

- https://portal.cloud.hashicorp.com/vagrant/discover/opensuse/Tumbleweed.x86_64

The configuration (vagrant file) is:

```
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
```

The image works as expected but if you `update` or `dup` the image won't boot, you will ned to modify  `.vagrant.d/boxes/opensuse-VAGRANTSLASH-Tumbleweed.x86_64/1.0.20241025/virtualbox/vagrantfile` line 3 to:

```
virtualbox.customize ["modifyvm", :id, "--ioapic", "off"]
```

You will be able to start the VM but it will take a lot of time to start but after a reboot seems it will work fine.

Question: since this repository seems is not being updated were can we find the info with the latest updates for the VM images?

**Comment by oliverhr** [comment] 2025-07-06 06:29
Seems all happen here now:

- https://build.opensuse.org/package/show/openSUSE:Factory:ToTest/kiwi-images-vagrant

the file with the issue:
https://build.opensuse.org/projects/openSUSE:Factory:ToTest/packages/kiwi-images-vagrant/files/virtualbox_vagrantfile?expand=1

**Comment by oliverhr** [comment] 2025-07-06 09:42
If `ioapic` is `on` the item section inside `<VirtualHardwareSection>` for the processor should set at lease 2 CPU's

```
      <Item>
        <rasd:Caption>2 virtual CPU</rasd:Caption>
        <rasd:Description>Number of virtual CPUs</rasd:Description>
        <rasd:ElementName>2 virtual CPU(s)</rasd:ElementName>
        <rasd:InstanceID>1</rasd:InstanceID>
        <rasd:ResourceType>3</rasd:ResourceType>
        <rasd:VirtualQuantity>2</rasd:VirtualQuantity>
      </Item>
```
